import {
  mdiAccountCheckOutline,
  mdiAccountCircleOutline,
  mdiAccountOutline,
  mdiAccountVoice,
  mdiAlertCircleOutline,
  mdiAlertOutline,
  mdiApi,
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowUp,
  mdiBookOpenOutline,
  mdiBrain,
  mdiBrushOutline,
  mdiCancel,
  mdiCast,
  mdiCastConnected,
  mdiChartArc,
  mdiChartBar,
  mdiChartLine,
  mdiChatOutline,
  mdiCheck,
  mdiCheckCircleOutline,
  mdiCheckDecagramOutline,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiContrastCircle,
  mdiClipboardCheckOutline,
  mdiClockOutline,
  mdiClose,
  mdiCloudDownloadOutline,
  mdiCloudOutline,
  mdiCloudSyncOutline,
  mdiCloudUploadOutline,
  mdiCodeJson,
  mdiCodeTags,
  mdiCogOutline,
  mdiConsole,
  mdiContentCopy,
  mdiContentSaveOutline,
  mdiCookieOutline,
  mdiDatabaseOutline,
  mdiDeleteOutline,
  mdiDevices,
  mdiDnsOutline,
  mdiDownloadOutline,
  mdiEarth,
  mdiEqualizer,
  mdiExport,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFileDocumentOutline,
  mdiFileTreeOutline,
  mdiFileUploadOutline,
  mdiFlaskOutline,
  mdiFolderOpenOutline,
  mdiFormatText,
  mdiGavel,
  mdiGraphOutline,
  mdiHandHeart,
  mdiHelpCircleOutline,
  mdiHistory,
  mdiImageMultipleOutline,
  mdiImageOutline,
  mdiImageSearchOutline,
  mdiImport,
  mdiInformationOutline,
  mdiKeyOutline,
  mdiLan,
  mdiLayersOutline,
  mdiLightningBolt,
  mdiLinkOff,
  mdiLinkVariant,
  mdiLoading,
  mdiLockOpenOutline,
  mdiLockOutline,
  mdiLogout,
  mdiMagnify,
  mdiMemory,
  mdiMenu,
  mdiMicrophoneOutline,
  mdiMonitor,
  mdiMinus,
  mdiMovieOutline,
  mdiMusicNoteOutline,
  mdiOfficeBuildingOutline,
  mdiOpenInNew,
  mdiPaperclip,
  mdiPause,
  mdiPencilOutline,
  mdiPiggyBankOutline,
  mdiPlay,
  mdiPlayCircleOutline,
  mdiPlaylistPlus,
  mdiPlus,
  mdiPower,
  mdiPowerOff,
  mdiPuzzleOutline,
  mdiQrcodeScan,
  mdiRadioboxBlank,
  mdiRefresh,
  mdiRestart,
  mdiRestore,
  mdiRobotOutline,
  mdiRocketLaunchOutline,
  mdiRoutes,
  mdiSendOutline,
  mdiShieldCheckOutline,
  mdiShieldLockOutline,
  mdiShieldOutline,
  mdiSourceBranch,
  mdiStarOutline,
  mdiStop,
  mdiStopCircleOutline,
  mdiSync,
  mdiSwapHorizontal,
  mdiToggleSwitch,
  mdiToggleSwitchOffOutline,
  mdiTranslate,
  mdiUploadOutline,
  mdiVideoOutline,
  mdiViewDashboardOutline,
  mdiViewGridOutline,
  mdiVolumeHigh,
  mdiVpn,
  mdiWifiOff,
  mdiWeatherNight,
  mdiWeatherSunny,
  mdiWeb,
  mdiWifi,
} from "@mdi/js";

/** Material Symbols name → @mdi/js path. UI icon SSOT for HAI-Router. */
export const MDI_ICON_REGISTRY = Object.freeze({
  account_circle: mdiAccountCircleOutline,
  account_tree: mdiFileTreeOutline,
  add: mdiPlus,
  remove: mdiMinus,
  api: mdiApi,
  arrow_back: mdiArrowLeft,
  arrow_downward: mdiArrowDown,
  arrow_forward: mdiArrowRight,
  arrow_upward: mdiArrowUp,
  attach_file: mdiPaperclip,
  bar_chart: mdiChartBar,
  block: mdiCancel,
  bolt: mdiLightningBolt,
  brush: mdiBrushOutline,
  business: mdiOfficeBuildingOutline,
  cancel: mdiCancel,
  chat: mdiChatOutline,
  check: mdiCheck,
  check_circle: mdiCheckCircleOutline,
  checklist: mdiClipboardCheckOutline,
  chevron_left: mdiChevronLeft,
  chevron_right: mdiChevronRight,
  close: mdiClose,
  cloud: mdiCloudOutline,
  cloud_download: mdiCloudDownloadOutline,
  cloud_upload: mdiCloudUploadOutline,
  code: mdiCodeTags,
  computer: mdiMonitor,
  content_copy: mdiContentCopy,
  contrast: mdiContrastCircle,
  cookie: mdiCookieOutline,
  dashboard: mdiViewDashboardOutline,
  data_array: mdiDatabaseOutline,
  data_object: mdiCodeJson,
  data_usage: mdiChartArc,
  delete: mdiDeleteOutline,
  description: mdiFileDocumentOutline,
  dns: mdiDnsOutline,
  download: mdiDownloadOutline,
  edit: mdiPencilOutline,
  error: mdiAlertCircleOutline,
  expand_less: mdiChevronUp,
  expand_more: mdiChevronDown,
  extension: mdiPuzzleOutline,
  file_upload: mdiFileUploadOutline,
  folder_open: mdiFolderOpenOutline,
  gavel: mdiGavel,
  grid_view: mdiViewGridOutline,
  health_and_safety: mdiShieldCheckOutline,
  help: mdiHelpCircleOutline,
  history: mdiHistory,
  hub: mdiGraphOutline,
  image: mdiImageOutline,
  image_search: mdiImageSearchOutline,
  info: mdiInformationOutline,
  input: mdiImport,
  key: mdiKeyOutline,
  keyboard_arrow_down: mdiChevronDown,
  keyboard_arrow_up: mdiChevronUp,
  lan: mdiLan,
  language: mdiWeb,
  layers: mdiLayersOutline,
  light_mode: mdiWeatherSunny,
  dark_mode: mdiWeatherNight,
  link: mdiLinkVariant,
  link_off: mdiLinkOff,
  lock: mdiLockOutline,
  lock_open: mdiLockOpenOutline,
  logout: mdiLogout,
  memory: mdiMemory,
  menu: mdiMenu,
  menu_book: mdiBookOpenOutline,
  mic: mdiMicrophoneOutline,
  monitor: mdiMonitor,
  monitoring: mdiChartLine,
  movie: mdiMovieOutline,
  music_note: mdiMusicNoteOutline,
  neurology: mdiBrain,
  open_in_new: mdiOpenInNew,
  output: mdiExport,
  pause: mdiPause,
  perm_media: mdiImageMultipleOutline,
  person: mdiAccountOutline,
  play_arrow: mdiPlay,
  play_circle: mdiPlayCircleOutline,
  playlist_add: mdiPlaylistPlus,
  power_off: mdiPowerOff,
  power_settings_new: mdiPower,
  progress_activity: mdiLoading,
  psychology: mdiBrain,
  record_voice_over: mdiAccountVoice,
  refresh: mdiRefresh,
  restart_alt: mdiRestart,
  restore: mdiRestore,
  rocket_launch: mdiRocketLaunchOutline,
  route: mdiRoutes,
  save: mdiContentSaveOutline,
  savings: mdiPiggyBankOutline,
  schedule: mdiClockOutline,
  science: mdiFlaskOutline,
  search: mdiMagnify,
  security: mdiShieldOutline,
  send: mdiSendOutline,
  settings: mdiCogOutline,
  shield: mdiShieldOutline,
  shield_lock: mdiShieldLockOutline,
  smart_toy: mdiRobotOutline,
  star: mdiStarOutline,
  stop: mdiStop,
  stop_circle: mdiStopCircleOutline,
  sync: mdiSync,
  sync_alt: mdiSwapHorizontal,
  terminal: mdiConsole,
  text_fields: mdiFormatText,
  toggle_on: mdiToggleSwitch,
  toggle_off: mdiToggleSwitchOffOutline,
  translate: mdiTranslate,
  travel_explore: mdiEarth,
  upload: mdiUploadOutline,
  upload_file: mdiFileUploadOutline,
  verified_user: mdiAccountCheckOutline,
  videocam: mdiVideoOutline,
  radio_button_unchecked: mdiRadioboxBlank,
  verified: mdiCheckDecagramOutline,
  visibility: mdiEyeOutline,
  visibility_off: mdiEyeOffOutline,
  volunteer_activism: mdiHandHeart,
  volume_up: mdiVolumeHigh,
  vpn_key: mdiVpn,
  vpn_lock: mdiVpn,
  warning: mdiAlertOutline,
  wifi: mdiWifi,
  wifi_tethering: mdiCastConnected,
  cast: mdiCast,
  qr_code_scanner: mdiQrcodeScan,
  wifi_off: mdiWifiOff,
  devices: mdiDevices,
  shield_with_heart: mdiHandHeart,
  cloud_sync: mdiCloudSyncOutline,
  graphic_eq: mdiEqualizer,
});

export function resolveMdiPath(name) {
  if (!name) return null;
  return MDI_ICON_REGISTRY[name] ?? null;
}

export function hasMdiIcon(name) {
  return Boolean(resolveMdiPath(name));
}
